import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const styles = readFileSync('src/styles.css', 'utf8')

describe('selective system swipe containment', () => {
  it('allows root history gestures while containing gestures inside carousels', () => {
    expect(styles).toContain('html,body,#root{')
    expect(styles).not.toContain('html{overscroll-behavior-x:none}')
    expect(styles).toContain('html[data-carousel-navigation-guard="true"]{overscroll-behavior-x:none}')
    expect(styles).not.toContain('touch-action:pan-y pinch-zoom')
    expect(styles).toContain('.maria-works-carousel{')
    expect(styles).toContain('.maria-orbit-carousel{')
    expect(styles.match(/touch-action:none/g)).toHaveLength(2)
  })
})

describe('card scale route transition', () => {
  it('starts one live works entrance after native snapshots are ready', () => {
    expect(styles).toContain('::view-transition-new(works-hand){animation:none;opacity:0}')
    expect(styles).toContain('html[data-transition-route="works"]::view-transition-new(root){display:none}')
    expect(styles).toContain('html[data-transition-route="works"]::view-transition-new(works-carousel){display:none}')
    expect(styles).toContain('.maria-works-page:not(.is-scene-ready) .maria-works-hand{animation:none!important;opacity:0}')
    expect(styles).toContain('.maria-works-page.is-scene-ready .maria-works-hand{opacity:1;animation:maria-works-hand-enter')
    expect(styles).toContain('.maria-works-carousel.is-entering:not(.is-entry-active) .maria-works-deck-card{transform:')
    expect(styles).toContain('.maria-works-carousel.is-entering.is-entry-active .maria-works-deck-card{animation:maria-works-card-enter')
  })

  it('scales the selected card over a bidirectional dissolve on desktop and mobile', () => {
    expect(styles).not.toContain('@keyframes maria-route-in-forward')
    expect(styles).not.toContain('@keyframes maria-route-in-back')
    expect(styles).toContain('@keyframes maria-route-fade')
    expect(styles).toContain('animation:maria-route-fade .24s ease-out')
    expect(styles).toContain('view-transition-name:works-route')
    expect(styles).toContain('view-transition-name:about-route')
    expect(styles).toContain('::view-transition-group(works-route)')
    expect(styles).toContain('::view-transition-group(about-route)')
    expect(styles).toContain('animation-duration:.52s')
    expect(styles).toContain('@keyframes maria-route-dissolve-out{from{opacity:1}to{opacity:0}}')
    expect(styles).toContain('@keyframes maria-route-dissolve-in{from{opacity:0}to{opacity:1}}')
    expect(styles).toContain('html[data-transition-direction] .maria-card--works,html[data-transition-direction] .maria-card--hackathons,html[data-transition-direction] .maria-works-page,html[data-transition-direction] .maria-hackathons-page{view-transition-name:none}')
    expect(styles).toContain('html[data-transition-direction]::view-transition-old(root){display:block;animation:maria-route-dissolve-out .4s ease-out both;mix-blend-mode:normal}')
    expect(styles).toContain('html[data-transition-direction]::view-transition-new(root){animation:maria-route-dissolve-in .4s ease-out both;mix-blend-mode:normal}')
    expect(styles).toContain('html[data-transition-route="works"] .maria-card--works,html[data-transition-route="hackathons"] .maria-card--hackathons{view-transition-name:home-card-scale}')
    expect(styles).toContain('@keyframes maria-home-card-open{from{opacity:1;scale:1}to{opacity:0;scale:1.25}}')
    expect(styles).toContain('@keyframes maria-home-card-close{from{opacity:0;scale:1.25}to{opacity:1;scale:1}}')
    expect(styles).toContain('::view-transition-group(home-card-scale){animation:none;z-index:4}')
    expect(styles).toContain('html[data-transition-direction="forward"]::view-transition-old(home-card-scale){animation:maria-home-card-open .4s ease-out both;transform-origin:center}')
    expect(styles).toContain('html[data-transition-direction="back"]::view-transition-new(home-card-scale){animation:maria-home-card-close .4s ease-out both;transform-origin:center}')
    expect(styles).toContain('html[data-transition-direction]::view-transition-old(root),html[data-transition-direction]::view-transition-new(root),html[data-transition-direction="forward"]::view-transition-old(home-card-scale),html[data-transition-direction="back"]::view-transition-new(home-card-scale){animation-duration:.01ms!important}')
    expect(styles).not.toContain('html:has(.maria-card--works)::view-transition-group(works-route)')
    expect(styles).not.toContain('html:has(.maria-card--hackathons)::view-transition-group(about-route)')
    expect(styles).not.toContain('.maria-card--works,.maria-card--hackathons{view-transition-name:none}')
    expect(styles).not.toContain('@keyframes maria-mobile-works-reveal')
    expect(styles).not.toContain('@keyframes maria-mobile-about-reveal')
    expect(styles).not.toContain('::view-transition-new(works-route){animation:maria-mobile-works-reveal')
    expect(styles).not.toContain('::view-transition-old(about-route){animation:maria-mobile-about-collapse')
    expect(styles).toContain('::view-transition-image-pair(works-route),::view-transition-image-pair(about-route){isolation:auto}')
    expect(styles).toContain('::view-transition-old(works-route),::view-transition-old(about-route){animation:none;opacity:0}')
    expect(styles).toContain('::view-transition-new(works-route),::view-transition-new(about-route){animation:none;opacity:1}')
    expect(styles).toContain('::view-transition-group(works-route),::view-transition-group(about-route){z-index:1}')
    expect(styles).toContain('html[data-transition-route="works"]::view-transition-group(about-route){z-index:0}')
    expect(styles).toContain('html[data-transition-route="hackathons"]::view-transition-group(works-route){z-index:0}')
    expect(styles).toContain('.maria-route-content{animation:none!important}')
    expect(styles).not.toContain('.maria-works-card-transition{')
    expect(styles).not.toContain('maria-works-card-dive-in')
  })
})

describe('instant back control', () => {
  it('keeps the back button outside the route snapshot and never animates it', () => {
    expect(styles).toContain('.maria-back{')
    expect(styles).toContain('view-transition-name:back-control')
    expect(styles).toContain('::view-transition-group(back-control){animation:none;z-index:1001}')
    expect(styles).toContain('::view-transition-old(back-control){display:none}')
    expect(styles).toContain('::view-transition-new(back-control){animation:none;opacity:1}')
  })
})

describe('home cards flying perspective', () => {
  it('aims the inner edges toward the center and brings outer edges forward', () => {
    expect(styles).toContain('transform-origin:right center')
    expect(styles).toContain('transform-origin:left center')
    expect(styles).toContain('perspective(1100px) rotateY(8deg) rotateZ(-1deg)')
    expect(styles).toContain('perspective(1100px) rotateY(-8deg) rotateZ(1deg)')
    expect(styles).toContain('.maria-card__art{display:block;width:100%;height:100%;object-fit:fill;pointer-events:none}')
    expect(styles).toContain('.maria-card::before,.maria-card::after{display:none}')
    expect(styles).toContain('aspect-ratio:1.08')
    expect(styles).toContain('translateZ(42px)')
    expect(styles).toContain('perspective(900px) rotateY(5deg) rotateZ(-1deg)')
    expect(styles).toContain('perspective(900px) rotateY(-5deg) rotateZ(1deg)')
  })
})

describe('reference home card composition', () => {
  it('places the two tall cards symmetrically at the viewport edges', () => {
    expect(styles).toContain('.maria-card{width:24.2vw;height:46vh;aspect-ratio:auto')
    expect(styles).toContain('.maria-card--works{top:27%;left:-.35vw')
    expect(styles).toContain('.maria-card--hackathons{top:27%;right:-.35vw')
    expect(styles).toContain('.maria-card__art{display:block;width:100%;height:100%;object-fit:fill;pointer-events:none}')
    expect(styles).toContain("@import url('https://fonts.googleapis.com/css2?family=Comforter&display=swap')")
    expect(styles).toContain(".maria-card__label{position:absolute;z-index:2;left:50%;top:62%;transform:translate(-50%,-50%);font:400 clamp(54px,4.8vw,98px)/1 'Comforter',cursive")
  })
})

describe('mobile home card mirrored pair', () => {
  it('keeps both cards equal, aligned, and lightly aimed toward the center', () => {
    expect(styles).toContain('.maria-card{width:min(49vw,215px);height:auto;aspect-ratio:1.08;padding:0}')
    expect(styles).toContain('.maria-card--works{left:0;top:auto;bottom:clamp(76px,12vh,104px);transform:perspective(900px) rotateY(5deg) rotateZ(-1deg)}')
    expect(styles).toContain('.maria-card--hackathons{right:0;top:auto;bottom:clamp(76px,12vh,104px);transform:perspective(900px) rotateY(-5deg) rotateZ(1deg);z-index:11}')
    expect(styles).not.toContain('.maria-card--works{left:8px;top:auto;bottom:128px')
    expect(styles).not.toContain('.maria-card--hackathons{right:8px;top:auto;bottom:24px')
  })
})

describe('home light portrait artwork', () => {
  it('fills the home viewport with the supplied landscape image', () => {
    expect(styles).toContain('.maria-home-portrait--light{inset:0;width:100%;height:100%;object-fit:cover;object-position:center;transform:none}')
    expect(styles).toContain('.maria-home-portrait--dark{transform:translate(-50%,-48%)}')
    expect(styles).toContain('.maria-home-portrait--dark{transform:translate(-50%,-56%)}')
  })
})

describe('shared chrome typography and grid', () => {
  it('switches every themed layer atomically without pausing persistent animations', () => {
    expect(styles).toContain('html[data-theme-switching="true"] .maria-app,html[data-theme-switching="true"] .maria-app *,html[data-theme-switching="true"] .maria-app *::before,html[data-theme-switching="true"] .maria-app *::after{transition:none!important}')
    expect(styles).not.toContain('html[data-theme-switching="true"] .maria-app *{animation:none')
  })

  it('keeps the browser root dark behind route transition snapshots', () => {
    expect(styles).toContain('html[data-theme="dark"],html[data-theme="dark"] body,html[data-theme="dark"] #root{background:#05070d}')
  })

  it('uses identical fixed-control sizing and offsets on every route', () => {
    expect(styles).toContain('.maria-header{position:fixed;z-index:40;left:24px;right:24px;top:24px;')
    expect(styles).toContain('font-size:clamp(14px,1vw,18px);white-space:nowrap;view-transition-name:fixed-header')
    expect(styles).toContain('.maria-avatar{width:42px;height:42px;overflow:hidden;border-radius:12px}')
    expect(styles).toContain('.maria-contact{display:flex;align-items:center;gap:3px;padding:10px 8px;border:0;background:transparent;')
    expect(styles).toContain('.maria-contact span{position:relative;top:-.08em;font-size:1.15em;line-height:1}')
    expect(styles).toContain('.maria-controls{position:fixed;z-index:40;left:24px;right:24px;bottom:24px;')
    expect(styles).toContain('font-size:16px;view-transition-name:fixed-controls')
    expect(styles).toContain('.maria-languages button{padding:4px 2px;opacity:.34;cursor:pointer}')
    expect(styles).toContain('.maria-theme button{width:24px;height:24px;display:grid;place-items:center;opacity:.34;cursor:pointer}')
    expect(styles).toContain('.maria-theme button img{display:block;max-width:100%;height:24px;object-fit:contain}')
    expect(styles).toContain('.theme-dark .maria-theme button img{filter:invert(1)}')
    expect(styles).toContain('.maria-languages .is-active,.maria-theme .is-active{opacity:1}')
    expect(styles).not.toContain('.maria-app:has(.maria-page)>.maria-header')
    expect(styles).not.toContain('.maria-app:has(.maria-page)>.maria-controls')
    expect(styles).toContain('.maria-header{grid-template-columns:auto 1fr auto;left:16px;right:16px;gap:10px}')
    expect(styles).toContain('.maria-controls{left:16px;right:16px}')
    expect(styles).toContain('.maria-header{grid-template-columns:34px 1fr auto;left:16px;right:16px;top:16px;column-gap:12px;row-gap:4px;font-size:15px}')
    expect(styles).toContain('.maria-avatar{grid-row:1/3;grid-column:1;align-self:center;width:34px;height:34px}')
    expect(styles).toContain('.maria-contact{grid-row:2;grid-column:3;justify-self:end;align-self:start;justify-content:flex-end;padding:0}.maria-contact span{display:inline;margin-left:0}')
    expect(styles).toContain('.maria-controls{left:16px;right:16px;bottom:16px;z-index:12;font-size:16.5px}')
    expect(styles).toContain('.maria-theme button{width:24px;height:24px}.maria-theme button img{height:24px}.maria-theme button:last-child img{height:26px}')
  })
})

describe('works hand entry and persistent fixed chrome', () => {
  it('lifts the hand from below while keeping shared controls above route transitions', () => {
    expect(styles).toContain('view-transition-name:works-hand')
    expect(styles).toContain('transform-origin:100% 54%')
    expect(styles).toContain('animation:maria-works-hand-enter .52s cubic-bezier(.2,.8,.2,1) both')
    expect(styles).toContain('@keyframes maria-works-hand-enter{from{transform:rotate(-48deg)}to{transform:rotate(0)}}')
    expect(styles).toContain('::view-transition-new(works-hand)')
    expect(styles).toContain('@keyframes maria-works-hand-enter-mobile{from{transform:rotate(-36deg)}to{transform:rotate(0)}}')
    expect(styles).toContain('view-transition-name:works-carousel')
    expect(styles).toContain('::view-transition-group(works-route),::view-transition-group(about-route){z-index:1}')
    expect(styles).toContain('::view-transition-group(works-hand){animation:none;z-index:2}')
    expect(styles).toContain('::view-transition-group(works-carousel){z-index:3}')
    expect(styles).toContain('view-transition-name:fixed-header')
    expect(styles).toContain('view-transition-name:fixed-controls')
    expect(styles).toContain('::view-transition-group(fixed-header),::view-transition-group(fixed-controls){animation:none;z-index:1000}')
    expect(styles).not.toContain('::view-transition-group(fixed-header),::view-transition-group(fixed-controls){animation-duration:.01ms')
    expect(styles).toContain('::view-transition-old(fixed-header),::view-transition-old(fixed-controls){animation:none;mix-blend-mode:normal}')
    expect(styles).toContain('::view-transition-new(fixed-header),::view-transition-new(fixed-controls){display:none}')
    expect(styles).toContain('::view-transition-new(works-hand){animation:none!important}')
  })
})

describe('inverse home return', () => {
  it('keeps the route shared elements active while returning home', () => {
    expect(styles).not.toContain('html:has(.maria-card--works)::view-transition-group(works-route)')
    expect(styles).not.toContain('html:has(.maria-card--hackathons)::view-transition-group(about-route)')
    expect(styles).not.toContain('html:has(.maria-card--works)::view-transition-old(works-route)')
    expect(styles).not.toContain('html:has(.maria-card--hackathons)::view-transition-old(about-route)')
    expect(styles).not.toContain('html:has(.maria-card--works)::view-transition-new(works-route)')
    expect(styles).not.toContain('html:has(.maria-card--hackathons)::view-transition-new(about-route)')
    expect(styles).not.toContain('hackathons-astronaut')
    expect(styles).not.toContain('hackathons-carousel')
    expect(styles).not.toContain('maria-astronaut-enter')
    expect(styles).not.toContain('.maria-model-entry')
  })
})

describe('about page astronaut entry', () => {
  it('rolls only the transparent model viewer without tilting its fullscreen container', () => {
    expect(styles).not.toContain('.maria-hackathons-page .maria-model-pose{animation:maria-about-model-enter')
    expect(styles).not.toContain('@keyframes maria-about-model-enter')
    expect(styles).toContain('.maria-hackathons-page .maria-model-viewer{transform-origin:50% 58%;animation:maria-about-model-roll .52s cubic-bezier(.2,.8,.2,1) both}')
    expect(styles).toContain('@keyframes maria-about-model-roll{from{transform:rotateZ(45deg)}to{transform:rotateZ(0)}}')
    expect(styles).not.toContain('.maria-model-entry')
    expect(styles).not.toContain('view-transition-name:hackathons-astronaut')
  })

  it('hides only the built-in model loading bar', () => {
    expect(styles).toContain('.maria-model-viewer::part(default-progress-bar){display:none}')
  })
})

describe('about page space background', () => {
  it('colors one responsive pattern mask with separate light and dark palettes', () => {
    expect(styles).toContain('.maria-hackathons-page{height:100svh;overflow:hidden;isolation:isolate;background:radial-gradient(circle at 18% 12%,rgba(255,235,246,.64),transparent 34%),radial-gradient(circle at 82% 78%,rgba(217,237,255,.56),transparent 39%),#c9cbd1}')
    expect(styles).toContain("-webkit-mask-image:url('/assets/maria/about-space-pattern.svg');mask-image:url('/assets/maria/about-space-pattern.svg')")
    expect(styles).toContain('-webkit-mask-repeat:repeat;mask-repeat:repeat')
    expect(styles).toContain('-webkit-mask-size:clamp(360px,46vw,620px);mask-size:clamp(360px,46vw,620px)')
    expect(styles).toContain('mask-size:clamp(360px,46vw,620px);opacity:.56')
    expect(styles).toContain('.theme-dark .maria-hackathons-page{background:radial-gradient(circle at 20% 14%,rgba(125,20,84,.16),transparent 35%),radial-gradient(circle at 82% 76%,rgba(42,41,117,.16),transparent 42%),#050710}')
    expect(styles).toContain('.theme-dark .maria-hackathons-page::before{background:radial-gradient(circle at 18% 16%,rgba(255,244,251,.96),rgba(255,105,183,.84) 38%,rgba(124,226,255,.8) 70%,rgba(218,176,255,.88));opacity:.47}')
    expect(styles).not.toContain("background-image:url('/assets/maria/about-space-pattern.svg')")
    expect(styles).toContain('.maria-hackathons-porthole{')
    expect(styles).toContain('background:transparent;filter:none')
    expect(styles).toContain('.maria-hackathons-porthole::before{')
    expect(styles).toContain('border:1.5px solid rgba(255,214,234,.68)')
    expect(styles).toContain('0 0 22px rgba(255,154,205,.12)')
    expect(styles).toContain('.theme-dark .maria-hackathons-porthole::before{border-color:rgba(255,211,232,.5)')
    expect(styles).toContain('conic-gradient(from 214deg at 50% 50%')
    expect(styles).toContain('rgba(131,229,255,.28)')
    expect(styles).toContain('inset 22px -18px 44px rgba(128,226,255,.12)')
    expect(styles).toContain('rgba(120,224,255,.32)')
    expect(styles).toContain('inset 24px -20px 48px rgba(58,188,255,.14)')
  })
})

describe('works page composition', () => {
  it('uses the compact layout without resizing the presentation viewer', () => {
    expect(styles).toContain('.maria-works-page{--works-pattern-x:var(--works-pattern-desktop-x);--works-pattern-y:var(--works-pattern-desktop-y);isolation:isolate;background:#f9f7f7}')
    expect(styles).toContain('.maria-works-page::before')
    expect(styles).toContain("url('/assets/maria/works-vector-pattern.svg')")
    expect(styles).toContain('background-size:cover')
    expect(styles).toContain('background-position:calc(50% + var(--works-pattern-x)) calc(50% + var(--works-pattern-y))')
    expect(styles).toContain('background-repeat:no-repeat')
    expect(styles).toContain('opacity:.5')
    expect(styles).not.toContain('background-image:linear-gradient(rgba(200,200,202,.38)')
    expect(styles).toContain('.theme-dark .maria-works-page{background:radial-gradient(circle at 22% 18%,rgba(78,10,45,.42),transparent 48%),radial-gradient(circle at 80% 78%,rgba(54,9,38,.32),transparent 46%),#030811}')
    expect(styles).toContain(".theme-dark .maria-works-page::before{background-image:url('/assets/maria/works-vector-pattern.svg');opacity:.24;filter:brightness(.32) saturate(.58) hue-rotate(-6deg)}")
    expect(styles).not.toContain('repeating-linear-gradient(112deg')
  expect(styles).toContain('.maria-works-hand{--works-hand-final-rotation:-90deg;--works-hand-x:0;--works-hand-y:0;position:absolute;z-index:1;left:50%;right:auto;')
  expect(styles).toContain('.maria-works-hand__image--alternate{position:absolute;left:0;top:-5px;bottom:auto;opacity:0}')
    expect(styles).toContain('--works-hand-final-rotation:-90deg')
    expect(styles).toContain('bottom:-52vh')
    expect(styles).toContain('translate:-18.2% 0')
    expect(styles).toContain('width:min(55vw,940px)')
    expect(styles).toContain('transform:translate3d(var(--works-hand-x),var(--works-hand-y),0) rotate(var(--works-hand-final-rotation))')
    expect(styles).not.toContain('.maria-works-grid{')
    expect(styles).toContain('.maria-works-carousel')
    expect(styles).toContain('.works-project-card{')
    expect(styles).toContain('--works-card-wall-overlap:2px;--works-card-footer-arc-depth:clamp(30px,4.5vh,72px);--works-card-footer-arc-height:calc(7vh + var(--works-card-footer-arc-depth))')
    expect(styles).toContain('.mts-project-card::before,.works-project-card::before{content:"";position:absolute;z-index:1;inset:0 0 calc(25% - var(--works-card-wall-overlap));height:auto;border-radius:11.111cqi 11.111cqi 0 0;background:var(--works-card-back);box-shadow:none')
    expect(styles).toContain('.mts-project-card__media,.works-project-card__media{position:absolute;z-index:2;left:6.5%;right:6.5%;top:-18%;height:96%;max-height:none;border-radius:0;background:transparent;overflow:visible')
    expect(styles).toContain('opacity:0;transform:scale(.667);transform-origin:50% 100%;transition:transform .64s cubic-bezier(.22,.72,.22,1),opacity .28s ease')
    expect(styles).toContain('.works-project-card.is-placeholder .works-project-card__media{top:-8%}')
    expect(styles).toContain('.maria-works-deck-card.is-centered .mts-project-card__media,.maria-works-deck-card.is-centered .works-project-card__media{opacity:1;transform:scale(1.12)}')
    expect(styles).toContain('.maria-works-deck-card.has-mts-game.is-centered .mts-game-card__artwork{opacity:1}')
    expect(styles).toContain('.mts-game-card__phones{position:absolute;z-index:5;left:50%;top:-26%;width:96%;max-width:none;height:auto;display:block;opacity:1;transform:translate3d(-50%,4%,0) scale(.59)')
    expect(styles).toContain('.maria-works-deck-card.is-centered .mts-project-card__media,.maria-works-deck-card.is-centered .works-project-card__media{opacity:1;transform:scale(1.12)}')
    expect(styles).toContain('.maria-works-deck-card.has-mts-game.is-centered .mts-game-card__phones{transform:translate3d(-50%,-2%,0) scale(.95)}')
    expect(styles).toContain('border-radius:11.111cqi')
    expect(styles).not.toContain('-webkit-mask:url(\'/assets/maria/works-card-mask.svg\')')
    expect(styles).toContain('.works-project-card__footer{position:absolute;z-index:4;left:0;right:0;bottom:0;height:calc(25% + var(--works-card-wall-overlap));box-sizing:border-box;')
    expect(styles).toContain('.mts-project-card__footer,.works-project-card__footer,.mts-game-card__footer,.rarible-project-card__footer,.aliexpress-project-card__footer,.tinnotech-project-card__footer,.wallet-project-card__footer{overflow:visible;isolation:isolate;background:transparent}')
    expect(styles).toContain('.mts-project-card__footer::before,.works-project-card__footer::before,.mts-game-card__footer::before,.rarible-project-card__footer::before,.aliexpress-project-card__footer::before,.tinnotech-project-card__footer::before,.wallet-project-card__footer::before{content:"";position:absolute;z-index:0;left:-4%;right:-4%;top:calc(-1 * var(--works-card-footer-arc-height));bottom:0;background:var(--works-card-footer);border-radius:11.111cqi;-webkit-mask-image:url("data:image/svg+xml,%3Csvg')
    expect(styles).toContain("preserveAspectRatio='none'%3E%3Cpath fill='black' d='M0 18 C0 10 5 5 12 5 C22 5 29 14 38 22")
    expect(styles).toContain("C44 28 47 33 50 33 C53 33 56 28 62 22 C71 14 78 5 88 5 C95 5 100 10 100 18")
    expect(styles).toContain('-webkit-mask-size:100% 100%;mask-size:100% 100%;-webkit-mask-repeat:no-repeat;mask-repeat:no-repeat;pointer-events:none}')
    expect(styles).toContain('.mts-project-card__footer>*,.works-project-card__footer>*,.mts-game-card__footer>*,.rarible-project-card__footer>*,.aliexpress-project-card__footer>*,.tinnotech-project-card__footer>*,.wallet-project-card__footer>*{position:relative;z-index:1}')
    expect(styles).toContain('.mts-project-card__footer>[class*="copy"],.works-project-card__footer>[class*="copy"],.mts-game-card__footer>[class*="copy"],.rarible-project-card__footer>[class*="copy"],.aliexpress-project-card__footer>[class*="copy"],.tinnotech-project-card__footer>[class*="copy"],.wallet-project-card__footer>[class*="copy"]{transform:translateY(-1.4cqi) scale(1.08);transform-origin:left center}')
    expect(styles).toContain('.mts-project-card__footer>[class*="file-icon"],.works-project-card__footer>[class*="file-icon"],.mts-game-card__footer>[class*="file-icon"],.rarible-project-card__footer>[class*="file-icon"],.aliexpress-project-card__footer>[class*="file-icon"],.tinnotech-project-card__footer>[class*="file-icon"],.wallet-project-card__footer>[class*="file-icon"]{width:clamp(39px,3.64vw,55px);height:clamp(39px,3.64vw,55px);transform:translateY(-1.4cqi) scale(1.05)}')
    expect(styles).toContain('.theme-dark .works-project-card{')
    expect(styles).not.toContain('background:repeating-linear-gradient(90deg,#160711 0 2px,#2b0a1c 2px 3px)')
    expect(styles).not.toContain('.maria-works-deck-card.has-project .maria-works-deck-card__spine')
    expect(styles).toContain('0 32px 76px rgba(0,0,0,.3)')
    expect(styles).toContain('.mts-presentation{position:relative;width:min(82vw,calc(72vh * 1.7777778),1600px)')
  })
})

describe('works responsive card deck', () => {
  it('uses one full-screen optimized artwork instead of a repeated works pattern', () => {
    expect(styles).toContain(".maria-works-page::before{content:\"\";position:absolute;z-index:0;inset:-3%;background-image:url('/assets/maria/works-vector-pattern.svg');background-size:cover;background-position:calc(50% + var(--works-pattern-x)) calc(50% + var(--works-pattern-y));background-repeat:no-repeat;opacity:.5")
    expect(styles).toContain("url('/assets/maria/works-vector-pattern.svg')")
    expect(styles).not.toContain("url('/assets/maria/works-background.webp')")
  })

  it('opens visible work cards from a compact desktop and mobile stack', () => {
    expect(styles).toContain('.maria-works-carousel.is-entering.is-entry-active .maria-works-deck-card{animation:maria-works-card-enter .52s cubic-bezier(.2,.82,.24,1) both;animation-delay:calc(var(--works-entry-index) * 38ms)}')
    expect(styles).toContain('@keyframes maria-works-card-enter{from{transform:translate3d(calc(-50% + var(--works-entry-x)),calc(-50% + var(--works-entry-lift-y)),0) rotateY(var(--works-entry-rotate-y)) scale(.94)}to{transform:translate3d(calc(-50% + var(--works-row-x)),-50%,0) rotateY(var(--works-row-rotate-y)) scale(var(--works-row-scale))}}')
    expect(styles).toContain('@keyframes maria-works-card-enter-mobile{from{transform:translate3d(-50%,calc(-50% + var(--works-entry-y-mobile) + var(--works-entry-lift-y)),0) scale(.94)}to{transform:translate3d(-50%,calc(-50% + var(--works-deck-y-mobile)),0) scale(var(--works-deck-scale-mobile))}}')
    expect(styles).toContain('.maria-works-carousel.is-entering.is-entry-active .maria-works-deck-card{animation-name:maria-works-card-enter-mobile}')
    expect(styles).toContain('.maria-works-carousel.is-entering .maria-works-deck-card{animation:none!important}')
  })

  it('keeps the hanging MTS flags hidden during pointer and keyboard interaction', () => {
    expect(styles).toContain('.works-project-card__mts-flag{')
    expect(styles).toContain('.works-project-card__mts-flag img{')
    expect(styles).not.toContain('.works-project-card__mts-flag strong{')
    expect(styles).not.toContain('.maria-works-deck-card:hover .works-project-card__mts-flag')
    expect(styles).not.toContain('.maria-works-deck-card:focus-within .works-project-card__mts-flag')
    expect(styles).not.toContain('.maria-works-deck-card:active .works-project-card__mts-flag')
  })

  it('keeps the MTS cover in the same opaque card shell as placeholders', () => {
    expect(styles).toContain('.mts-project-card{position:relative;box-sizing:border-box;width:100%;height:100%;container-type:inline-size;overflow:visible')
    expect(styles).toContain('.mts-project-card::before,.works-project-card::before{content:"";position:absolute;z-index:1;inset:0 0 calc(25% - var(--works-card-wall-overlap));height:auto;border-radius:11.111cqi 11.111cqi 0 0;background:var(--works-card-back);box-shadow:none')
    expect(styles).toContain('.mts-project-card__artwork{position:absolute;z-index:2;inset:0;width:100%;height:100%;max-width:none;display:block;object-fit:contain;object-position:center bottom;image-rendering:-webkit-optimize-contrast;transform:translate3d(0,6%,0) scale(.84);transform-origin:50% 100%;transition:transform .72s cubic-bezier(.18,.76,.2,1);will-change:transform;pointer-events:none}')
    expect(styles).toContain('.maria-works-deck-card.is-centered .mts-project-card__artwork{transform:translate3d(0,0,0) scale(1)}')
    expect(styles).toContain('.mts-project-card__media{left:-12%;right:-12%;top:-18%;height:134%;clip-path:inset(-100vh -100vw 12% -100vw);transform:none;transition:opacity .28s ease}')
    expect(styles).toContain('.maria-works-deck-card.is-centered .mts-project-card__media{transform:none}')
    expect(styles).toContain('.mts-flyout-overlay{position:fixed;z-index:39;inset:0;overflow:visible;pointer-events:none;isolation:isolate}')
    expect(styles).toContain('.mts-flyout-overlay__logo,.mts-flyout-overlay__butterfly{position:absolute;display:block;max-width:none;height:auto;opacity:0;pointer-events:none;filter:blur(0);image-rendering:auto;transform-origin:center;will-change:opacity,filter}')
    expect(styles).toContain('.mts-flyout-overlay__butterfly{left:50%;top:35vh;width:clamp(70px,7.5vw,140px);filter:blur(0) drop-shadow(0 8px 14px rgba(155,175,255,.28));transform:translate(calc(-2% + 5vh),-50%) rotate(4deg) scale(.3)}')
    expect(styles).toContain('.mts-flyout-overlay.is-active .mts-flyout-overlay__butterfly{animation:mts-butterfly-flyout-to-viewer 1.68s cubic-bezier(.18,.72,.16,1) .06s both}')
    expect(styles).not.toContain('rgba(255,150,205')
    expect(styles).not.toContain('.maria-works-deck-card.is-centered .mts-project-card__logo-flyout{animation:')
    expect(styles).not.toContain('.maria-works-deck-card.is-centered .mts-project-card__butterfly-flyout{animation:')
    expect(styles).toContain('transform:translate(calc(-587% - 5vh),-202%) rotate(-46deg) scale(13)')
    expect(styles).toContain('transform:translate(calc(487% + 5vh),-202%) rotate(46deg) scale(13)')
    expect(styles).toContain('.mts-project-card__footer{position:absolute;z-index:4;left:0;right:0;bottom:0;height:calc(25% + var(--works-card-wall-overlap));box-sizing:border-box;')
    expect(styles).toContain('.maria-works-deck-card.has-project{box-shadow:none;filter:none}')
    expect(styles).toContain('.maria-works-deck-card.has-project.is-centered{z-index:100}')
    expect(styles).toContain('.mts-project-card:hover,.mts-project-card:focus-visible{transform:none}')
    expect(styles).not.toContain('.mts-project-card:hover,.mts-project-card:focus-visible{transform:none;box-shadow:none}')
    expect(styles).not.toContain('.concept-cover__external-artwork')
    expect(styles).not.toContain('.works-project-card__breakout-artwork{')
    expect(styles).not.toContain('.has-breakout-artwork')
  })

  it('lays equal cards horizontally on desktop and vertically on mobile', () => {
    expect(styles).toContain('.maria-works-carousel{position:absolute;z-index:3;')
    expect(styles).toContain('position:absolute;left:50%;top:50%;width:clamp(336px,36vw,672px);height:clamp(220px,23.61vw,441px);')
    expect(styles).toContain('width:clamp(336px,36vw,672px);height:clamp(220px,23.61vw,441px);overflow:visible;border:0;border-radius:11.111cqi;background:transparent;box-shadow:none;filter:saturate')
    expect(styles).not.toContain('aspect-ratio:432/360')
    expect(styles).not.toContain('aspect-ratio:432/418')
    expect(styles).toContain('.works-project-card{position:relative;box-sizing:border-box;width:100%;height:100%;container-type:inline-size;overflow:visible;')
    expect(styles).toContain('.mts-project-card__media,.works-project-card__media{position:absolute;z-index:2;left:6.5%;right:6.5%;top:-18%;height:96%;max-height:none;border-radius:0;background:transparent;overflow:visible;opacity:0;transform:scale(.667);transform-origin:50% 100%;transition:transform .64s cubic-bezier(.22,.72,.22,1),opacity .28s ease}')
    expect(styles).not.toContain('border-radius:10.185cqi')
    expect(styles).toContain('.works-project-card__file-icon{display:grid;place-items:center;width:clamp(24px,2.25vw,34px);')
    expect(styles).toContain(".mts-project-card__file-icon,.works-project-card__file-icon,.mts-game-card__file-icon,.rarible-project-card__file-icon,.aliexpress-project-card__file-icon,.tinnotech-project-card__file-icon,.wallet-project-card__file-icon{background:transparent;color:inherit;border-radius:0}")
    expect(styles).toContain(".mts-project-card__file-icon::before,.works-project-card__file-icon::before,.mts-game-card__file-icon::before,.rarible-project-card__file-icon::before,.aliexpress-project-card__file-icon::before,.tinnotech-project-card__file-icon::before,.wallet-project-card__file-icon::before{content:\"\";display:block;width:100%;height:100%;background:url('/assets/maria/project-file-icon.svg') center/contain no-repeat}")
    expect(styles).toContain('.mts-project-card__file-icon svg,.works-project-card__file-icon svg,.mts-game-card__file-icon svg,.rarible-project-card__file-icon svg,.aliexpress-project-card__file-icon svg,.tinnotech-project-card__file-icon svg,.wallet-project-card__file-icon svg{display:none}')
    expect(styles).not.toContain('.autopay-project-card .wallet-project-card__file-icon{background:#168cff}')
    expect(styles).toContain('.works-project-card__title{overflow:hidden;font-size:clamp(13px,1.15vw,20px);')
    const unifiedTitleRule = '.mts-project-card__title,.works-project-card__title,.mts-game-card__title,.rarible-project-card__title,.aliexpress-project-card__title,.tinnotech-project-card__title,.wallet-project-card__title{font-family:\'Comforter\',cursive;font-size:clamp(28px,calc(1.45vw + 12px),38px);font-weight:400;letter-spacing:0;line-height:1;overflow:visible;text-overflow:clip}'
    expect(styles).toContain(unifiedTitleRule)
    expect(styles.indexOf(unifiedTitleRule)).toBe(styles.lastIndexOf(unifiedTitleRule))
    expect(styles).toContain('.works-project-card__meta{overflow:hidden;color:rgba(38,27,34,.58);font-size:clamp(10px,.8vw,14px);')
    expect(styles).toContain('.mts-project-card__meta,.works-project-card__meta,.mts-game-card__meta,.rarible-project-card__meta,.aliexpress-project-card__meta,.tinnotech-project-card__meta,.wallet-project-card__meta{color:#111!important;font-size:clamp(10px,.8vw,14px);line-height:1.2}')
    const unifiedMetaRule = '.mts-project-card__meta,.works-project-card__meta,.mts-game-card__meta,.rarible-project-card__meta,.aliexpress-project-card__meta,.tinnotech-project-card__meta,.wallet-project-card__meta{font-size:clamp(10px,.8vw,14px);font-weight:400;letter-spacing:0;line-height:1.2}'
    expect(styles).toContain(unifiedMetaRule)
    expect(styles).toContain('.mts-project-card__copy,.works-project-card__copy,.mts-game-card__copy,.rarible-project-card__copy,.aliexpress-project-card__copy,.tinnotech-project-card__copy,.wallet-project-card__copy{min-width:0;height:clamp(42px,4vw,60px);display:flex;flex-direction:column;justify-content:center;gap:clamp(2px,.35vw,6px);margin-left:0;padding-left:0}')
    expect(styles).toContain('.maria-works-deck-card.has-rarible .rarible-project-card__meta,.maria-works-deck-card.has-mts-game .mts-game-card__meta,.maria-works-deck-card.has-tinnotech .tinnotech-project-card__meta,.theme-dark .maria-works-deck-card:not(:nth-child(4n+1)):not(.has-project):not(.has-aliexpress) .works-project-card__meta,.theme-dark .maria-works-deck-card.has-rarible .rarible-project-card__meta,.theme-dark .maria-works-deck-card.has-mts-game .mts-game-card__meta,.theme-dark .maria-works-deck-card.has-tinnotech .tinnotech-project-card__meta{color:#fff!important}')
    expect(styles).toContain('.theme-dark .maria-works-deck-card.has-wallet .wallet-project-card,.theme-dark .maria-works-deck-card.has-autopay .wallet-project-card,.theme-dark .maria-works-deck-card.has-sbp .wallet-project-card,.theme-dark .maria-works-deck-card.has-connection .wallet-project-card{color:#17131b}')
    expect(styles).toContain('.theme-dark .maria-works-deck-card.has-wallet .wallet-project-card__meta,.theme-dark .maria-works-deck-card.has-autopay .wallet-project-card__meta,.theme-dark .maria-works-deck-card.has-sbp .wallet-project-card__meta,.theme-dark .maria-works-deck-card.has-connection .wallet-project-card__meta{color:rgba(23,19,27,.68)!important}')
    expect(styles).toContain('background-position:calc(50% + var(--works-pattern-x)) calc(50% + var(--works-pattern-y))')
    expect(styles).toContain('perspective:1800px')
    expect(styles).not.toContain('.maria-works-deck-card__label')
    expect(styles).not.toContain('.maria-works-deck-card__spine')
    expect(styles).not.toContain('.maria-works-deck-card__pages')
    expect(styles).toContain('transform:translate3d(calc(-50% + var(--works-row-x)),-50%,0)')
    expect(styles).toContain('scale(var(--works-row-scale))')
    expect(styles).toContain('transform-origin:50% 28%')
    expect(styles).toContain('scale:1')
    expect(styles).toContain('transition:transform 1.25s cubic-bezier(.22,.62,.28,1),scale .22s ease,box-shadow .3s ease')
    expect(styles).toContain('.maria-works-carousel.is-wheeling .maria-works-deck-card{transition:none}')
    expect(styles).not.toContain('transition:transform .2s')
    expect(styles).toContain('user-select:none')
    expect(styles).toContain('html[data-carousel-navigation-guard="true"]{overscroll-behavior-x:none}')
    expect(styles).toContain('.maria-works-carousel{position:absolute;z-index:3;left:0;right:0;top:16vh;height:58vh;overflow:visible;perspective:1800px;touch-action:none;overscroll-behavior-x:contain;')
    expect(styles).toContain('-webkit-user-drag:none')
    expect(styles).toContain('var(--works-deck-y-mobile)')
    expect(styles).toContain('var(--works-deck-scale-mobile)')
    expect(styles).not.toContain('var(--works-deck-opacity-mobile)')
    expect(styles).toContain('var(--works-deck-layer-mobile)')
    expect(styles).not.toContain('rotateZ(var(--works-deck-rotate-z-mobile))')
    expect(styles).not.toContain('rotateX(var(--works-deck-rotate-x-mobile))')
    expect(styles).toContain('.maria-works-deck-card{width:84.042vw;height:79.373vw;opacity:1;z-index:var(--works-deck-layer-mobile);transform:translate3d(-50%,calc(-50% + var(--works-deck-y-mobile)),0) scale(var(--works-deck-scale-mobile));transition:transform 1.25s cubic-bezier(.22,.62,.28,1),filter .2s ease}')
    expect(styles).toContain('.maria-works-deck-card.has-project{width:84.042vw;height:79.373vw}')
    expect(styles).toContain('opacity:1')
    expect(styles).toContain('@media(hover:hover) and (pointer:fine)')
    expect(styles).toContain('.maria-works-deck-card.is-hidden{opacity:0;visibility:hidden;pointer-events:none}')
    expect(styles).toContain('background:transparent')
    expect(styles).not.toContain('border:1px solid rgba(72,49,62,.18)')
    expect(styles).toContain('left:6.5%;right:6.5%;top:-18%;height:96%')
    expect(styles).not.toContain('.works-project-card{padding:4px;clip-path:inset(0 round 22px)}')
    expect(styles).toContain('overflow:hidden')
    expect(styles).toContain('.works-project-card__file-icon{')
    expect(styles).toContain('font-weight:500')
    expect(styles).toContain('transform-origin:50% 28%')
    expect(styles).toContain('width:clamp(336px,36vw,672px)')
    expect(styles).toContain('.maria-works-deck-card{--works-card-back:')
    expect(styles).toContain('height:clamp(220px,23.61vw,441px);overflow:visible;border:0;')
    expect(styles).not.toContain('.maria-works-deck-card::after')
    expect(styles).not.toContain('clip-path:polygon(0 0,100% 0,62% 100%,38% 100%)')
    expect(styles).not.toContain('.theme-dark .maria-works-deck-card::after{')
    expect(styles).not.toContain('filter:brightness(var(--works-card-brightness-light))')
    expect(styles).toContain('filter:saturate(var(--works-card-saturation-light))')
    expect(styles).toContain('will-change:auto;transition:transform 1.25s')
    expect(styles).toContain('@media(min-width:1200px){')
    expect(styles).toContain('.maria-works-deck-card,.theme-dark .maria-works-deck-card{filter:none}')
    expect(styles).not.toContain('.works-project-card::after{')
    expect(styles).not.toContain('.theme-dark .works-project-card::after{')
    expect(styles).not.toContain('.theme-light .works-project-card::after{')
    expect(styles).toContain('.theme-dark .maria-works-deck-card{filter:saturate(var(--works-card-saturation-dark)) hue-rotate(var(--works-card-dark-hue))')
    expect(styles).toContain('0 0 42px rgba(255,70,164,var(--works-card-dark-glow))')
    expect(styles).not.toContain('filter:brightness(var(--works-card-brightness-dark))')
    expect(styles).not.toContain('var(--works-deck-scale)')
    expect(styles).not.toContain('var(--works-deck-opacity)')
    expect(styles).toContain('.mts-project-card:focus-visible{outline:none}')
    expect(styles).toContain('.maria-works-deck-card:hover{scale:1.035}')
    expect(styles).toContain('.maria-works-deck-card:focus-within{scale:1.035}')
    expect(styles).toContain('.maria-works-carousel.is-dragging .maria-works-deck-card{scale:1;transition:none}')
    expect(styles).not.toContain('maria-works-motion-blur')
    expect(styles).not.toContain('blur(2.4px)')
    expect(styles).not.toContain('blur(1.15px)')
    expect(styles).toContain('.mts-project-card:hover,.mts-project-card:focus-visible{transform:none}')
    expect(styles).not.toContain('.mts-project-card:hover,.mts-project-card:focus-visible{transform:none;box-shadow:none}')
    expect(styles).not.toContain('0 0 0 2px rgba(255,255,255,.82)')
    expect(styles).not.toContain('0 0 0 3px var(--pink)')
    expect(styles).toContain('@media(max-width:600px)')
    expect(styles).toContain('.maria-works-carousel{position:absolute;z-index:3;left:0;right:0;top:16vh;height:58vh;')
    expect(styles).toContain('.maria-works-carousel{top:calc(50% - 2vh);height:0;overflow:visible}')
    expect(styles).not.toContain('.maria-works-deck-card.is-mobile-lower{display:none}')
    expect(styles).toContain('.maria-works-hand{bottom:-19vh;width:118vw}')
    expect(styles).toContain('.maria-works-deck-card{width:84.042vw;height:79.373vw;opacity:1;z-index:var(--works-deck-layer-mobile);transform:translate3d(-50%,calc(-50% + var(--works-deck-y-mobile)),0) scale(var(--works-deck-scale-mobile));transition:transform 1.25s cubic-bezier(.22,.62,.28,1),filter .2s ease}')
    expect(styles).toContain('.maria-works-carousel.is-dragging .maria-works-deck-card{transition:none}')
    expect(styles).not.toContain('.theme-light .maria-works-deck-card::before{')
    expect(styles).toContain('.maria-back{position:fixed;z-index:45;left:24px;top:86px;')
    expect(styles).toContain('.maria-back{left:16px;top:calc(94px - 1vh);font-size:36px}')
    expect(styles).toContain('.maria-works-page .maria-back{top:calc(94px - 1vh)}')
    expect(styles).toContain('@media(prefers-reduced-motion:reduce)')
    expect(styles).toContain('.maria-works-deck-card{transition:none}')
  })
})

describe('works card inner color and image hierarchy', () => {
  it('uses themed opaque gradients and enlarges media only in the centered card', () => {
    expect(styles).toContain('.theme-dark .mts-project-card::before,.theme-dark .works-project-card::before{background:var(--works-card-back);box-shadow:none}')
    expect(styles).toContain('.works-project-card__image,.works-project-card__image.concept-cover__image{position:absolute;z-index:2;inset:0;width:100%;height:100%;max-width:none;display:block;object-fit:contain')
    expect(styles).not.toContain('.maria-works-deck-card.is-centered .works-project-card__image{transform:')
    expect(styles).toContain('transform-origin:50% 100%;transition:transform .64s cubic-bezier(.22,.72,.22,1)')
    expect(styles).toContain('.maria-works-deck-card.is-centered .mts-project-card__media,.maria-works-deck-card.is-centered .works-project-card__media{opacity:1;transform:scale(1.12)}')
    expect(styles).toContain('object-fit:contain;pointer-events:none}')
  })

  it('builds the card from an opaque rear panel and a foreground wall without SVG layers', () => {
    expect(styles).toContain('.mts-project-card::before,.works-project-card::before{content:"";position:absolute;z-index:1;inset:0 0 calc(25% - var(--works-card-wall-overlap));height:auto;border-radius:11.111cqi 11.111cqi 0 0;background:var(--works-card-back)')
    expect(styles).toContain('.maria-works-deck-card:nth-child(4n+1){--works-card-back:radial-gradient(circle at 18% 18%,#fbfdff 0 24%,transparent 48%),radial-gradient(circle at 72% 24%,#dcecff 0 26%,transparent 54%),radial-gradient(circle at 70% 86%,#cbdcff 0 28%,transparent 58%),#f1f5ff;--works-card-footer:radial-gradient(circle at 16% 18%,#fbfdff 0 30%,transparent 62%),#eaf2ff}')
    expect(styles).toContain('.maria-works-deck-card.has-project{--works-card-back:radial-gradient(circle at 18% 18%,#fbfdff 0 24%,transparent 48%),radial-gradient(circle at 72% 24%,#dcecff 0 25%,transparent 52%),radial-gradient(circle at 76% 82%,#ffdbe7 0 30%,transparent 60%),#fff8fb;--works-card-footer:radial-gradient(circle at 14% 20%,#fffafd 0 26%,transparent 58%),radial-gradient(circle at 72% 18%,#edf5ff 0 28%,transparent 60%),#ffeef6}')
    expect(styles).toContain('.maria-works-deck-card.has-rarible{--works-card-back:radial-gradient(circle at 18% 18%,#211347 0 24%,transparent 48%),radial-gradient(circle at 72% 24%,#43206f 0 25%,transparent 52%),radial-gradient(circle at 74% 82%,#8e6711 0 30%,transparent 60%),#67278d;--works-card-footer:radial-gradient(circle at 14% 20%,#251853 0 28%,transparent 60%),radial-gradient(circle at 72% 24%,#3e2470 0 30%,transparent 62%),#2a194d;--works-card-footer-edge:rgba(221,202,255,.24)}')
    expect(styles).toContain('.maria-works-deck-card.has-aliexpress{--works-card-back:radial-gradient(circle at 18% 18%,#fffaf6 0 24%,transparent 48%),radial-gradient(circle at 74% 24%,#ffe8d8 0 26%,transparent 54%),radial-gradient(circle at 72% 86%,#ffd0bd 0 30%,transparent 60%),#fff2eb;--works-card-footer:radial-gradient(circle at 16% 18%,#fffaf8 0 30%,transparent 62%),#ffeadd}')
    expect(styles).toContain('.maria-works-deck-card.has-mts-game{--works-card-back:radial-gradient(circle at 18% 18%,#08133d 0 24%,transparent 48%),radial-gradient(circle at 72% 24%,#1b2c70 0 25%,transparent 52%),radial-gradient(circle at 76% 82%,#8f223c 0 30%,transparent 60%),#4e1b74;--works-card-footer:radial-gradient(circle at 14% 20%,#10194c 0 28%,transparent 60%),radial-gradient(circle at 72% 24%,#25235f 0 30%,transparent 62%),#321c4e;--works-card-footer-edge:rgba(198,209,255,.2)}')
    expect(styles).toContain('.theme-dark .maria-works-deck-card:nth-child(4n+1){--works-card-back:radial-gradient(circle at 18% 18%,#f4fbff 0 24%,transparent 48%),radial-gradient(circle at 74% 24%,#c6e8ff 0 26%,transparent 54%),radial-gradient(circle at 70% 86%,#b8d5ff 0 30%,transparent 60%),#eaf3ff;--works-card-footer:radial-gradient(circle at 16% 18%,#f8fbff 0 30%,transparent 62%),#dcecff}')
    expect(styles).toContain('.theme-dark .maria-works-deck-card.has-rarible{--works-card-back:radial-gradient(circle at 18% 18%,#120933 0 24%,transparent 48%),radial-gradient(circle at 72% 24%,#30157a 0 25%,transparent 52%),radial-gradient(circle at 76% 82%,#6729c7 0 30%,transparent 60%),#2a105d;--works-card-footer:radial-gradient(circle at 14% 20%,#120a31 0 30%,transparent 62%),#32166a}')
    expect(styles).toContain('.theme-dark .maria-works-deck-card.has-aliexpress{--works-card-back:radial-gradient(circle at 18% 18%,#fff8f2 0 24%,transparent 48%),radial-gradient(circle at 74% 24%,#ffd8c9 0 26%,transparent 54%),radial-gradient(circle at 72% 86%,#ffbfa5 0 30%,transparent 60%),#ffe8dd;--works-card-footer:radial-gradient(circle at 16% 18%,#fff8f4 0 30%,transparent 62%),#ffd8ca}')
    expect(styles).toContain('.theme-dark .maria-works-deck-card.has-mts-game{--works-card-back:radial-gradient(circle at 18% 18%,#07133a 0 24%,transparent 48%),radial-gradient(circle at 72% 24%,#122a75 0 25%,transparent 52%),radial-gradient(circle at 76% 82%,#a52a43 0 30%,transparent 60%),#5b1a83;--works-card-footer:radial-gradient(circle at 14% 20%,#08143c 0 26%,transparent 58%),radial-gradient(circle at 72% 18%,#1d2868 0 28%,transparent 60%),#421550}')
    expect(styles).toContain('.theme-dark .maria-works-deck-card:nth-child(4n+1) .works-project-card,.theme-dark .maria-works-deck-card.has-project .mts-project-card,.theme-dark .maria-works-deck-card.has-aliexpress .aliexpress-project-card{color:#19131b}')
    expect(styles).not.toContain('height:78%;border-radius:inherit')
    expect(styles).toContain('background:var(--works-card-footer);border-radius:0 0 11.111cqi 11.111cqi;box-shadow:none')
    expect(styles).toContain('overflow:visible;isolation:isolate;background:transparent')
    expect(styles).toContain('top:calc(-1 * var(--works-card-footer-arc-height));bottom:0;background:var(--works-card-footer);border-radius:11.111cqi;-webkit-mask-image:url("data:image/svg+xml,%3Csvg')
    expect(styles).toContain("C22 5 29 14 38 22 C44 28 47 33 50 33 C53 33 56 28 62 22")
    expect(styles).toContain('.theme-dark .mts-project-card__footer,.theme-dark .works-project-card__footer{background:transparent;box-shadow:none}')
    expect(styles).not.toContain('works-project-card-back.svg')
    expect(styles).not.toContain('works-project-card-front.svg')
  })

  it('keeps the exact Figma geometry without translucent deck overlays', () => {
    expect(styles).toContain('height:clamp(220px,23.61vw,441px)')
    expect(styles).not.toContain('aspect-ratio:432/360')
    expect(styles).not.toContain('aspect-ratio:432/418')
    expect(styles).toContain('border-radius:11.111cqi')
    expect(styles).not.toContain('border-radius:10.185cqi')
    expect(styles).not.toContain('.works-project-card::after{')
    expect(styles).not.toContain('.theme-light .maria-works-deck-card::before{')
    expect(styles).not.toContain('.theme-dark .works-project-card::after{')
    expect(styles).not.toContain('.maria-works-deck-card::after{')
    expect(styles).toContain('.mts-project-card__media,.works-project-card__media{position:absolute;z-index:2;left:6.5%;right:6.5%;top:-18%;height:96%;max-height:none;border-radius:0;background:transparent;overflow:visible')
    expect(styles).toContain('.works-project-card{position:relative;box-sizing:border-box;width:100%;height:100%;container-type:inline-size;overflow:visible;border:0;border-radius:inherit;background:transparent')
    expect(styles).not.toContain('box-shadow:0 30px 70px rgba(22,4,14,.18)')
    expect(styles).not.toContain('outline:1px solid #fffafb')
    expect(styles).toContain('isolation:isolate;mix-blend-mode:normal')
    expect(styles).toContain('opacity:1;visibility:visible;transform:translateZ(.2px);backface-visibility:hidden')
    expect(styles).toContain('padding:calc(2.4cqi + var(--works-card-wall-overlap)) 5.5cqi 3.1cqi')
    expect(styles).toContain('.mts-project-card__media::before,.works-project-card__media::before,.works-project-card__media::after,.mts-project-card__media::after{display:none}')
    expect(styles).not.toContain('top:-44.828%')
    expect(styles).not.toContain('height:171.983%')
  })
})

describe('layered MTS game card', () => {
  it('reveals layered project compositions with continuous centered-state transitions', () => {
    expect(styles).toContain('.mts-game-card{position:relative;box-sizing:border-box;width:100%;height:100%;container-type:inline-size;overflow:visible;')
    expect(styles).toContain('.mts-game-card__artwork{position:absolute;z-index:2;inset:0 0 25%;overflow:visible;clip-path:inset(-100vh -100vw 0 -100vw);')
    expect(styles).toContain('.mts-game-card__statue{position:absolute;z-index:3;')
    expect(styles).toContain('.mts-game-card__girl{position:absolute;z-index:6;')
    expect(styles).toContain('.mts-game-card__phones{position:absolute;z-index:5;')
    expect(styles).toContain('.mts-game-card__footer{position:absolute;z-index:20;')
    expect(styles).toContain('.maria-works-deck-card.has-mts-game.is-centered{z-index:110}')
    expect(styles).toContain('.maria-works-deck-card.has-mts-game.is-centered .mts-game-card__girl{opacity:1;')
    expect(styles).toContain('.maria-works-deck-card.has-mts-game.is-centered .mts-game-card__statue{opacity:1;')
    expect(styles).toContain('.maria-works-deck-card.has-mts-game.is-centered .mts-game-card__phones{transform:')
    expect(styles).toContain('.mts-game-card__phones{position:absolute;z-index:5;left:50%;top:-26%;width:96%;')
    expect(styles).toContain('.mts-game-card__girl{position:absolute;z-index:6;left:-16%;top:-5%;width:62%;')
    expect(styles).toContain('.mts-game-card__statue{position:absolute;z-index:3;right:-24%;top:-19%;width:71%;')
    expect(styles).toContain('.maria-works-deck-card.has-mts-game.is-centered .mts-game-card__phones{transform:translate3d(-50%,-2%,0) scale(.95)}')
    expect(styles).toContain('transition:transform .84s cubic-bezier(.16,.82,.18,1),opacity .28s ease;will-change:transform,opacity')
    expect(styles).toContain('transition:transform .86s cubic-bezier(.16,.82,.18,1),opacity .28s ease;will-change:transform,opacity')
    expect(styles).toContain('.maria-works-deck-card.has-rarible.is-centered .rarible-project-card__ape{opacity:1;transform:translate3d(-14%,calc(5% - 7cqi),0) rotate(-11deg) scale(.96)}')
    expect(styles).toContain('.maria-works-deck-card.has-rarible.is-centered .rarible-project-card__logo{opacity:1;transform:translate3d(16%,calc(1% - 9.625cqi),0) rotate(11deg) scale(.96)}')
    expect(styles).toContain('.maria-works-deck-card.has-aliexpress.is-centered .aliexpress-project-card__bag{opacity:1;transform:translate3d(-14%,calc(5% - 5.25cqi),0) rotate(-14deg) scale(.96)}')
    expect(styles).toContain('.maria-works-deck-card.has-aliexpress.is-centered .aliexpress-project-card__heart{opacity:1;transform:translate3d(24%,calc(5% - 5.25cqi),0) rotate(13deg) scale(.96)}')
    expect(styles).toContain('.maria-works-deck-card.has-aliexpress.is-centered .aliexpress-project-card__sparkles{opacity:1;transform:translate3d(0,3%,0) rotate(12deg) scale(.96)}')
    expect(styles).not.toContain('@keyframes mts-game-girl-enter')
    expect(styles).not.toContain('@keyframes mts-game-statue-enter')
    expect(styles).not.toContain('@keyframes rarible-ape-enter')
    expect(styles).not.toContain('@keyframes rarible-logo-enter')
    expect(styles).not.toContain('@keyframes aliexpress-bag-enter')
    expect(styles).not.toContain('.mts-game-card:hover')
  })
})

describe('works centered corner ribbon', () => {
  it('wraps the next placeholder corner and keeps its tail gently moving while centered', () => {
    expect(styles).toContain('.works-corner-ribbon{position:absolute;z-index:9;right:-5%;top:-8%;width:48%;')
    expect(styles).toContain('.works-corner-ribbon__wrap{fill:none;stroke-linecap:round;stroke-dasharray:360;stroke-dashoffset:360')
    expect(styles).toContain('.maria-works-deck-card.is-centered .works-corner-ribbon__wrap{animation:works-ribbon-wrap .9s cubic-bezier(.2,.76,.22,1) forwards}')
    expect(styles).toContain('.maria-works-deck-card.is-centered .works-corner-ribbon__wrap--front{animation-delay:.18s}')
    expect(styles).toContain('.maria-works-deck-card.is-centered .works-corner-ribbon__tail{animation:works-ribbon-tail-in .38s ease-out .78s forwards,works-ribbon-sway 2.4s ease-in-out 1.16s infinite alternate}')
    expect(styles).toContain('@keyframes works-ribbon-wrap')
    expect(styles).toContain('@keyframes works-ribbon-sway')
    expect(styles).toContain('@media(prefers-reduced-motion:reduce){.works-corner-ribbon{display:none}}')
  })
})

describe('works centered MTS flyout layers', () => {
  it('throws the Figma logo and butterfly toward the viewer before fading them at the end', () => {
    expect(styles).toContain('.mts-flyout-overlay__logo{left:50%;top:38vh;width:clamp(67px,7.2vw,134px);transform:translate(calc(-98% - 5vh),-50%) rotate(-4deg) scale(.28)}')
    expect(styles).toContain('.mts-flyout-overlay__butterfly{left:50%;top:35vh;width:clamp(70px,7.5vw,140px);filter:blur(0) drop-shadow(0 8px 14px rgba(155,175,255,.28));transform:translate(calc(-2% + 5vh),-50%) rotate(4deg) scale(.3)}')
    expect(styles).toContain('.mts-flyout-overlay.is-active .mts-flyout-overlay__logo{animation:mts-logo-flyout-to-viewer 1.58s cubic-bezier(.18,.72,.16,1) both}')
    expect(styles).toContain('.mts-flyout-overlay.is-active .mts-flyout-overlay__butterfly{animation:mts-butterfly-flyout-to-viewer 1.68s cubic-bezier(.18,.72,.16,1) .06s both}')
    expect(styles).toContain('@keyframes mts-logo-flyout-to-viewer{0%{opacity:0;filter:blur(0);transform:')
    expect(styles).toContain('94%{opacity:1;filter:blur(12px);transform:translate(calc(-450% - 5vh),-158%)')
    expect(styles).toContain('100%{opacity:0;filter:blur(42px);transform:translate(calc(-587% - 5vh),-202%)')
    expect(styles).toContain('@keyframes mts-butterfly-flyout-to-viewer{0%{opacity:0;filter:blur(0) drop-shadow(0 8px 14px rgba(155,175,255,.28));transform:')
    expect(styles).toContain('94%{opacity:1;filter:blur(12px) drop-shadow(0 8px 14px rgba(155,175,255,.28));transform:translate(calc(350% + 5vh),-158%)')
    expect(styles).not.toContain('@keyframes mts-logo-flyout-to-viewer{0%{opacity:0;filter:blur(0);transform:translate3d(')
    expect(styles).toContain('@media(max-width:600px){.mts-flyout-overlay__logo{top:48vh;width:17.28vw}.mts-flyout-overlay__butterfly{top:46.5vh;width:18vw}}')
    expect(styles).toContain('@media(prefers-reduced-motion:reduce){.mts-flyout-overlay{display:none}}')
  })
})

describe('mobile works card artwork geometry', () => {
  it('uses the desktop artwork positions on mobile instead of separate mobile offsets', () => {
    expect(styles).toContain('.mts-game-card__girl{position:absolute;z-index:6;left:-16%;top:-5%;width:62%;')
    expect(styles).toContain('.mts-game-card__statue{position:absolute;z-index:3;right:-24%;top:-19%;width:71%;')
    expect(styles).toContain('.mts-game-card__phones{position:absolute;z-index:5;left:50%;top:-26%;width:96%;')
    expect(styles).toContain('.rarible-project-card__ape{position:absolute;z-index:6;left:-7%;top:13%;width:47%;')
    expect(styles).toContain('.rarible-project-card__logo{position:absolute;z-index:6;right:-5%;top:42%;width:42%;')
    expect(styles).not.toContain('.mts-game-card__girl{left:-15%;top:-2%;width:56%}')
    expect(styles).not.toContain('.mts-game-card__statue{right:-21%;top:-14%;width:65%}')
    expect(styles).not.toContain('.mts-game-card__phones{left:50%;top:-24%;width:92%}')
    expect(styles).not.toContain('.rarible-project-card__ape{left:-5%;top:14%;width:44%}')
    expect(styles).not.toContain('.rarible-project-card__logo{right:-4%;top:43%;width:39%}')
  })

  it('keeps centered project artwork offsets relative to the card instead of the viewport', () => {
    expect(styles).toContain('.maria-works-deck-card.has-tinnotech.is-centered .tinnotech-project-card__phones{transform:translate3d(-50%,calc(1% + 8.75cqi),0) scale(1.02)}')
    expect(styles).toContain('.maria-works-deck-card.has-wallet.is-centered .wallet-project-card__phones{transform:translate3d(-48.5%,calc(1% - 7cqi),0) scale(.99)}')
    expect(styles).toContain('.maria-works-deck-card.has-autopay.is-centered .autopay-project-card__arrows{opacity:1;transform:translate3d(-7%,calc(-9% + 10.5cqi - 13vh),0) rotate(-8deg) scale(1.03)}')
    expect(styles).toContain('.maria-works-deck-card.has-autopay.is-centered .autopay-project-card__phones{transform:translate3d(-50%,calc(1% + 5.25cqi - 2vh),0) scale(1.02);animation:autopay-phones-enter .84s cubic-bezier(.16,.82,.18,1) both}')
    expect(styles).toContain('.autopay-project-card__phones{z-index:6;left:50%;top:-22%;width:95%;transform:translate3d(-50%,18%,0) scale(.42);transform-origin:50% 72%;transition:transform .84s cubic-bezier(.16,.82,.18,1)}')
    expect(styles).toContain('@keyframes autopay-phones-enter{0%{transform:translate3d(-50%,18%,0) scale(.42)}100%{transform:translate3d(-50%,calc(1% + 5.25cqi - 2vh),0) scale(1.02)}}')
    expect(styles).not.toContain('.tinnotech-project-card__phones{transform:translate3d(-50%,calc(1% + 3vh),0) scale(.95)}')
    expect(styles).not.toContain('.wallet-project-card__phones{transform:translate3d(-46.5%,calc(1% - 7vh),0) scale(.93)}')
    expect(styles).not.toContain('.autopay-project-card__arrows{opacity:1;transform:translate3d(6%,calc(-9% + 6vh),0) rotate(-8deg) scale(1.03)}')
  })

  it('drops mobile phone artwork lower into the footer curve on dense cards', () => {
    expect(styles).toContain('@media(max-width:600px)')
    expect(styles).toContain('.works-project-card__mts-flag{right:5%;width:66px}.maria-works-deck-card.has-tinnotech.is-centered .tinnotech-project-card__phones{transform:translate3d(-50%,calc(1% + 10.5cqi),0) scale(1.08)}')
    expect(styles).toContain('.maria-works-deck-card.has-wallet.is-centered .wallet-project-card__phones{transform:translate3d(-46.5%,calc(1% - 5.25cqi),0) scale(1.04)}')
    expect(styles).toContain('.maria-works-deck-card.has-autopay.is-centered .autopay-project-card__phones{transform:translate3d(-50%,calc(1% + 7cqi),0) scale(1.08)}')
    expect(styles).not.toContain('.maria-works-deck-card.has-autopay.is-centered .autopay-project-card__phones{transform:translate3d(-50%,-2%,0) scale(.94)}')
  })
})

describe('hackathon orbit placeholders', () => {
  it('styles decorative cards without pointer interaction', () => {
    expect(styles).toContain('.maria-orbit-carousel{position:absolute;inset:0;overflow:hidden;pointer-events:auto;touch-action:none;overscroll-behavior-x:contain;')
    expect(styles).toContain('.maria-orbit-carousel__gesture-zone{position:absolute;pointer-events:none;left:2vw;right:2vw;bottom:4vh;height:62vh}')
    expect(styles).toContain('.maria-orbit-card--placeholder{pointer-events:none')
    expect(styles).toContain('.maria-orbit-card--placeholder::after')
    expect(styles).toContain('width:clamp(178px,48vw,195px)')
    expect(styles).toContain('var(--orbit-x-mobile)')
    expect(styles).toContain('var(--orbit-y-mobile)')
  })
})
